### ISSUE TITLE
Update 7OCT2024 Infinity_Hammer 1.59.0 (JereKuusela) stops structure support boosts.

### ISSUE THREAD

**Issue by PatMacRoin** [blaxxun-boop/Building#11]
Other recent JereKuusela updates correspond with the issue since last time I logged into Valheim:

Server_devcommands 1.83.0 (Update 2OCT2024)
World_Edit_Commands 1.63.0 (Update 2OCT2024)

The result before and after:

**_Before_** - At most advantageous factor (0.01), Horizonal beam of 8 flamemetal beams out sustains as deep green in accordance with this structure pattern:

<--------------[Horizontal Flamemetal Base]---------------->[HF1][HF2][HFn...][HF8] (All still deep green!)
[Vertical Flamemetal][Black Marble Block][Vertical Flamemetal]

**_After_** updates -

<--------------[Horizontal Flamemetal Base]---------------->[HF1][HF2][HFn...][HF8] (HF8 = Deep orange!)
[Vertical Flamemetal][Black Marble Block][Vertical Flamemetal]

**Comment by blaxxun-boop** [comment]
Okay, and why are you reporting that here and not to the author of Infinity Hammer?

**Comment by PatMacRoin** [comment]
Because I didn't know whether or not your stake or their stake had the majority slant of the programming. Excuse my ignorance. I'm just a mod consumer. That, and your mod didn't seem to be updated in quite a while comparatively. By chronology, I understood it prudent to let you know for sake of updating.

I will add here in case they give a similar response.
